name: example_flutter
description: An example project for flutter-desktop-embedding.

version: 0.1.0

environment:
  sdk: '>=2.0.0 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.10.2-pre.54'

dependencies:
  flutter:
    sdk: flutter
  modal_progress_hud:
  cupertino_icons: ^0.1.0
  carousel_slider: ^1.3.1
  simple_animations: ^1.3.4
  flutter_spinkit: ^4.1.1+1
  mysql1:
  font_awesome_flutter: ^8.5.0
  flutter_rating_bar: ^3.0.0+1
  fl_chart: ^0.6.0
  flutter_icons: ^1.0.0+1
  image_picker: ^0.6.2+3
  datetime_picker_formfield: ^1.0.0
  intl: 
  charts_flutter: ^0.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/info/
    - assets/instruments/Guitars/
    - assets/instruments/Drums/
    - assets/instruments/Piano/
    - assets/instruments/amp/
    - assets/avatars/

  # See https://github.com/flutter/flutter/wiki/Desktop-shells#fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Homemade
      fonts:
        - asset: fonts/Homemade/HomemadeApple-Regular.ttf
    - family: Kaushan
      fonts:
        - asset: fonts/Kaushan/KaushanScript-Regular.ttf
